version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      DB_URI: ${DB_URI}
      SECRET: ${SECRET}
      MAILTRAP_USERNAME: ${MAILTRAP_USERNAME}
      MAILTRAP_PASSWORD: ${MAILTRAP_PASSWORD}
    volumes:
      - .:/app
      - /app/node_modules
